name: Scheduled build

on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - name: Backup data
        run: >
          deno run
          --allow-read
          --allow-net
          --allow-write
          --no-check
          index.ts
      - name: Zip
        run: zip data data.json
      - name: Set Date
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "data.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CURRENT_DATETIME }}