name: Scheduled build

on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: denoland/setup-deno@v1
      # - name: Backup data
      #   run: >
      #     deno run --allow-read --allow-net --allow-write --no-check index.ts
      - name: Zip
        run: |
          echo "test" > test.csv
          zip release test.csv
      # - name: git setting
      #   run: |
      #     git config --global user.email "meganii@outlook.jp"
      #     git config --global user.name "meganii"
      # - name: Commit files
      #   run: |
      #     git add .
      #     git commit -m "Add backup data" -a
      #     git pull
      #     git push origin main