name: Scheduled build

on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          access_token_scopes: 'https://www.googleapis.com/auth/drive.metadata.readonly'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Download pages parquet file
        run: uv run src/download.py
    
      - name: Backup cosense project
        run: uv run src/main.py

      - name: Remove json pages
        run: rm villagepump/pages/*.json

      - name: Dump pages to JSONL and JSON files from Parquet
        run: uv run src/dump_parquet_to_json.py

      - name: JSONL to JSON
        run: |
          {
            echo '{"pages": ['
            sed '$!s/$/,/' data/data.jsonl
            echo ']}'
          } > data/data.json

      - name: Zip
        run: zip data/data data/data.json

      - name: Update Google Drive file
        run: uv run src/upload.py

      - name: Diff
        id: diff
        run: |
          git add -N villagepump/stats villagepump/pages
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit files
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add villagepump/stats villagepump/pages
          git commit -m "Update"
          git push
        if: steps.diff.outcome == 'failure'

      - name: Set Date
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "data/data.zip, data/pages.parquet"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CURRENT_DATETIME }}
