name: Scheduled build

on:
  schedule:
    - cron: 10 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name
        run: |
          echo "test" > test.csv
      - name: git setting
        run: |
          git config --local user.email "meganii@outlook.jp"
          git config --local user.name "meganii"
      - name: Commit files
        run: |
          git add .
          git commit -m "Add csv" -a
          git pull
          git push origin main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: denoland/setup-deno@v1
#       - run: >
#           deno run --allow-read --allow-net --allow-write --no-check index.ts
#       - name: git setting
#         run: |
#           git config --local user.email "meganii@outlook.jp"
#           git config --local user.name "meganii"
#       - name: Commit files
#         run: |
#           git add .
#           git commit -m "Add csv" -a
#           git pull
#           git push origin master