name: Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  job_id:
    # ...
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        access_token_scopes: 'https://www.googleapis.com/auth/drive.metadata.readonly'
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Run script
      run: python3 upload.py